[package]
name = "ark-drop"
version = "0.1.0"
description = "An app to sync files between devices"
authors = ["you"]
license = ""
repository = ""
default-run = "ark-drop"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
drop_core = { path = "../core" }
tauri = { version = "1.6.7", features = ["dialog-open"] }
hex = "0.4.3"
walkdir = "2.5.0"
flume = "0.11.0"
num_cpus = "1.16.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
dirs = "5.0.1"
open = "5.1.3"

serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
iroh = { workspace = true }
iroh-blobs = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
iroh-base = { workspace = true }
iroh-net = { workspace = true }
tokio = {  workspace = true , features = ["full"] }
tokio-util = { workspace = true }
futures-lite = { workspace = true }
futures-buffered = { workspace = true }




[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
