[package]
name = "ark-drop-desktop"
version = "0.1.0"
description = "An app to sync files between devices"
authors = ["you"]
edition = "2021"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ark_drop_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5.0.1"
open = "5.1.3"

iroh-blobs = { workspace = true }
iroh-base = { workspace = true }
anyhow = { workspace = true }

tokio = {  workspace = true , features = ["full"] }
tauri-plugin-dialog = "2"
tauri-plugin-clipboard-manager = "2.2.0"

