[workspace]
resolver = "2"
members = [
	"core",
	"src-tauri"
]

[workspace.dependencies]
iroh = "0.17.0"
iroh-blobs = "0.17.0"
iroh-base = "0.17.0"
iroh-net = "0.17.0"
anyhow = "1.0.86"
thiserror = "1.0.61"
futures-buffered = "0.2.6"
futures-lite = "2.3.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = "0.7.11"
bytes = "1.6.0"

