[package]
name = "drop_core"
version = "0.1.0"
edition = "2021"

[dependencies]
iroh = {workspace = true}
iroh-blobs = {workspace = true}
iroh-base = {workspace = true}
iroh-net = {workspace = true}
anyhow = {workspace = true}
thiserror = {workspace = true}
futures-buffered = {workspace = true}
futures-lite = {workspace = true}
serde = {workspace = true}
postcard = "1.0.8"